name: alice
description: Alice is an HTTP Inspector tool which helps debugging http
  requests. It catches and stores http requests and responses, which can be
  viewed via simple UI.
version: 0.2.5
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  chopper: ^4.0.3
  collection: ^1.15.0
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.0.1
  http: ^0.13.4
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.6
  permission_handler: ^8.2.6
  rxdart: ^0.27.2
  sensors: ^2.0.3
  share: ^2.0.4
  url_launcher: ^6.1.2

dev_dependencies:
  lint: ^1.7.2
